Split ldd and otool checks into separate step

diff --git a/.github/workflows/release.yaml b/.github/workflows/release.yaml
--- a/.github/workflows/release.yaml
+++ b/.github/workflows/release.yaml
@@ -296,17 +296,24 @@ jobs:
             --enable-static \
             $PLATFORM_CONFIGURE_FLAGS
           make
-          # Show that these are not dynamic executables.  Fail if they are.
+
+      - name: Check that executables are static
+        run: |
+          set -e
+          set -x
+          cd ffmpeg
           if [[ "${{ runner.os }}" == "Linux" ]]; then
+            # Show that these are not dynamic executables.  Fail if they are.
             ldd ffmpeg && exit 1
             ldd ffprobe && exit 1
+          elif [[ "${{ runner.os }}" == "Windows" ]]; then
+            # Show that these are not dynamic executables.  Fail if they are.
+            ldd ffmpeg.exe && exit 1
+            ldd ffprobe.exe && exit 1
           elif [[ "${{ runner.os }}" == "macOS" ]]; then
             # TODO: Verify the usage of otool for macOS.
             otool -L ffmpeg && exit 1
             otool -L ffprobe && exit 1
-          elif [[ "${{ runner.os }}" == "Windows" ]]; then
-            ldd ffmpeg.exe && exit 1
-            ldd ffprobe.exe && exit 1
           fi
           # After commands that we expect to fail, we still need a successful
           # command here to make this step a success.
