Adjust expectations for dynamic executables on Windows
I think this Windows build will finally pass!

diff --git a/.github/workflows/release.yaml b/.github/workflows/release.yaml
--- a/.github/workflows/release.yaml
+++ b/.github/workflows/release.yaml
@@ -41,7 +41,6 @@ jobs:
     needs: draft_release
     strategy:
       matrix:
-        # TODO: Work through Windows issues
         # TODO: Finish Mac
         # TODO: Add Mac arm64?
         # TODO: Add Windows arm64?
@@ -315,13 +314,17 @@ jobs:
           set -x
           cd ffmpeg
           if [[ "${{ runner.os }}" == "Linux" ]]; then
-            # Show that these are not dynamic executables.  Fail if they are.
+            # If ldd succeeds, then these are dynamic executables, so we fail
+            # this step if ldd succeeds.
             ldd ffmpeg && exit 1
             ldd ffprobe && exit 1
           elif [[ "${{ runner.os }}" == "Windows" ]]; then
-            # Show that these are not dynamic executables.  Fail if they are.
-            ldd ffmpeg.exe && exit 1
-            ldd ffprobe.exe && exit 1
+            # These will still be dynamic executables, but they should not link
+            # against anything outside of /c/Windows.  The grep command will
+            # succeed if it can find anything outside /c/Windows, and then we
+            # fail if that succeeds.
+            ldd ffmpeg.exe | grep -qvi /c/Windows/ && exit 1
+            ldd ffprobe.exe | grep -qvi /c/Windows/ && exit 1
           elif [[ "${{ runner.os }}" == "macOS" ]]; then
             # TODO: Verify the usage of otool for macOS.
             otool -L ffmpeg && exit 1
